# Generated by Django 5.2.17 on 2026-09-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='amount',
            field=models.PositiveIntegerField(help_text='Amount in smallest currency unit (e.g. 5000 = ₦50.00 if using kobo)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
    ]
